### ISSUE TITLE
【不具合】PgDn等が効かなくなる

### ISSUE THREAD

**Issue by yu-cha** [482F/kml-viewer#15]
マウス以外で頁送りができなくなる。
データのあるあたりをクリックすることで１回目キーでの頁送りができても、２回目はできなくなっていて、またデータのクリックが必要になる。

**Comment by yu-cha** [comment]
ツイッター用に作ってもらった頁送り機能のctrl+PgUPなども、使えない。

**Comment by yu-cha** [comment]
とりあえず画面右のスクロールバーをクリックしてからだと効く。

**Comment by 482F** [comment]
修正済み
