### ISSUE TITLE
複数項目で並べ替えがしたい

### ISSUE THREAD

**Issue by yu-cha** [482F/kml-viewer#17]
緯度経度で並べ替えがしたい #8　でやってくれた並べ替え、多分、１項目のみの並べ替えだと思います。
例えば、「緯度→経度→フォルダ名」で並べ替えをした場合、優先順位が「フォルダ名→経度→緯度」で並べ替えして欲しいです。

**Comment by yu-cha** [comment]
* い
* いうぇ
  * ええええががが

**Comment by 482F** [comment]
多分修正済み
